### ISSUE TITLE
Dependencies problem

### ISSUE THREAD

**Issue by cakeinpanic** [zacbarton/gulp-crash-sound#2]
Hello, half of year later i've tried to use you plugin again, but `npm i` fails on installing one of package dependencies
Please take a look

**Comment by AlexanderKozhevin** [comment]
Something badly wrong happens during installation. 

Well, I have a better idea how to notify about gulp error. 
First  - connect arduino via [Johny-five](https://github.com/rwaldron/johnny-five).
Then add any device. Like a led or sound alerter. Or go crazy and add [Relay](http://img.dxcdn.com/productimages/sku_149805_1.jpg) which control the lights at home :smile:.

![screen shot 2016-01-28 at 23 10 29](https://cloud.githubusercontent.com/assets/4464561/12657442/632f69f6-c614-11e5-8ec8-d39db9c2d69d.png)

**Comment by zacbarton** [comment]
Wow I cant really apologize for how long this has been outstanding but I've just pushed a new version that fixes the build issues (tested on node v5.5.0).

Sorry guys :-(
